version: '3.8'
services:
  rykelabs-strapi-app:
    image: git.rykelabs.com:5050/rykelabs/strapi/strapi:latest
    networks:
      - rykelabs-strapi-external
#    healthcheck:
#      test: wget --no-verbose --no-check-certificate --tries=1 --spider http://127.0.0.1:8080/ || exit 1
#      interval: 30s
#      timeout: 10s
#      retries: 3
